#' Example gold-labeled support answers
#'
#' A small synthetic dataset of support-style question/answer items, each rated
#' Correct / Partial / Incorrect by a human and by an example LLM judge. Used in
#' examples and `vignette("yourhonor")` to demonstrate judge calibration without a
#' live model call. The judge labels deliberately disagree with the human labels
#' on a minority of items so the agreement coefficients are realistic (not 1.0).
#'
#' @format A tibble with columns:
#' \describe{
#'   \item{id}{Item identifier.}
#'   \item{input}{The question and candidate answer presented to the judge.}
#'   \item{target}{The grading criterion.}
#'   \item{human_label}{Human rating, a factor with levels `I` < `P` < `C`.}
#'   \item{judge_label}{Example judge rating, same levels.}
#' }
#' @source Generated by `data-raw/support_gold.R`.
"support_gold"
